# Generated by Django 2.1.5 on 2020-08-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catégorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Entrer une catégorie de produit (exemple: Un ...)', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='forme',
            name='name',
            field=models.CharField(help_text='Entrer une forme de produit (exemple: Liquide ...)', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='catégorie',
            field=models.ManyToManyField(help_text='Selectionner une catégorie pour ce produit.', to='catalog.Catégorie'),
        ),
    ]
